# Generated by Django 4.1 on 2023-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('peratio', models.CharField(max_length=10)),
                ('weekup', models.CharField(max_length=10)),
                ('weekdown', models.CharField(max_length=10)),
            ],
        ),
    ]
