# Generated by Django 4.1 on 2023-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=50)),
                ('TotalShare', models.CharField(max_length=5)),
                ('TotalAmount', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
