# Generated by Django 4.1 on 2023-03-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_transaction_delete_contact_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
